#! /usr/bin/env python3

import itertools
import math

description = '''
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def root(a,b,c):
  return (-b + math.sqrt(b*b - 4*a*c)) / (2*a)
  
def isPentagonal(x):
  return root(3, -1, -2*x).is_integer()

def isTriangular(x):
  return root(1, 1, -2*x).is_integer()

def hexagonal(n): 
  return n * (2*n - 1)

hexagonals = (hexagonal(n) for n in itertools.count(1))
triPenHex = (x for x in hexagonals if isTriangular(x) and isPentagonal(x))

print(list(itertools.islice(triPenHex, 3))) #1, 40755, and result
 
